version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce
    working_directory: ~/workspace
    environment:
      DOCKER_OWNER: emojigen
      DOCKER_IMAGE: docker-libemoji
      DOCKER_TAG: stretch
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Install Bash
          command: |
            apk add -U -q --no-progress bash
      - run:
          name: Build
          command: docker build -t $DOCKER_OWNER/$DOCKER_IMAGE:latest .
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push image to registory
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag \
                $DOCKER_OWNER/$DOCKER_IMAGE:latest \
                $DOCKER_OWNER/$DOCKER_IMAGE:$DOCKER_TAG
              docker push $DOCKER_OWNER/$DOCKER_IMAGE
              docker push $DOCKER_OWNER/$DOCKER_IMAGE:$DOCKER_TAG
            fi
